[loggers]
keys=root,ldap_auth,auth_ldap_ldap_auth,pipeline,utils.db,werkzeug

[handlers]
keys=consoleHandler,ldapHandler,pipelineHandler,httpHandler,errorHandler,utilsDbHandler

[formatters]
keys=defaultFormatter,simpleFormatter

###########################################################
# FORMATTERS
###########################################################

[formatter_defaultFormatter]
format=%(asctime)s [%(levelname)s] (%(processName)s:%(threadName)s) %(message)s
datefmt=%Y-%m-%d %H:%M:%S

[formatter_simpleFormatter]
format=%(asctime)s [%(levelname)s] %(message)s
datefmt=%Y-%m-%d %H:%M:%S

###########################################################
# HANDLERS
###########################################################

[handler_consoleHandler]
class=logging.StreamHandler
level=INFO
formatter=defaultFormatter
args=(sys.stdout,)

# ldap_auth.log (CONCURRENTE)
[handler_ldapHandler]
class=concurrent_log_handler.ConcurrentRotatingFileHandler
level=INFO
formatter=defaultFormatter
args=("logs/ldap_auth.log", "a", 10485760, 5, "utf-8")

# pipeline.log (CONCURRENTE)
[handler_pipelineHandler]
class=concurrent_log_handler.ConcurrentRotatingFileHandler
level=INFO
formatter=defaultFormatter
args=("logs/pipeline.log", "a", 10485760, 5, "utf-8")

# http.log (CONCURRENTE)
[handler_httpHandler]
class=concurrent_log_handler.ConcurrentRotatingFileHandler
level=INFO
formatter=simpleFormatter
args=("logs/http.log", "a", 10485760, 5, "utf-8")

# error.log (CONCURRENTE)
[handler_errorHandler]
class=concurrent_log_handler.ConcurrentRotatingFileHandler
level=ERROR
formatter=defaultFormatter
args=("logs/error.log", "a", 10485760, 5, "utf-8")

[handler_utilsDbHandler]
class=concurrent_log_handler.ConcurrentRotatingFileHandler
level=INFO
formatter=defaultFormatter
args=("logs/db.log", "a", 10485760, 5, "utf-8")

###########################################################
# LOGGERS
###########################################################

[logger_root]
level=WARNING
handlers=consoleHandler,errorHandler

# Logger explícito para código que use logging.getLogger("ldap_auth")
[logger_ldap_auth]
level=INFO
handlers=ldapHandler
qualname=ldap_auth
propagate=0

# Logger REAL generado por módulos Python: auth_ldap/ldap_auth.py  ( __name__ = "auth_ldap.ldap_auth" )
[logger_auth_ldap_ldap_auth]
level=INFO
handlers=ldapHandler
qualname=auth_ldap.ldap_auth
propagate=0

[logger_pipeline]
level=INFO
handlers=pipelineHandler
qualname=pipeline
propagate=0

[logger_utils.db]
level=INFO
handlers=utilsDbHandler
qualname=utils.db
propagate=0

[logger_werkzeug]
level=INFO
handlers=httpHandler
qualname=werkzeug
propagate=0
