# Ejemplos de uso:
#
# msg = MESSAGES.errors("task_ctl_no_csv_files")
# logger.error(f"[{task_id}] {msg}")
# ..
# msg = MESSAGES.errors("task_ctl_no_csv_files", task_id=task_id)
# msg = MESSAGES.errors("proccess_dir_deletion", task_id=task_id, error=e)
# ...
# return jsonify({"error": msg}), 400

[errors]
app_no_file = No se ha enviado fichero
app_invalid_file = El fichero {filename} no es válido
task_ctl_no_csv_files = [{task_id}] No se encontraron CSVs para generar el CTL.
task_not_found = Tarea no encontrada
task_not_removable = No se puede borrar mientras se ejecuta
task_retry_error = La tarea no se pudo reintentar, no se pudo generar un nuevo id
task_comprobar_csv_no_dir = [{task_id}] Directorio no encontrado: {dir}
task_comprobar_csv_no_fmt = [{task_id}] Fichero de formato no encontrado para: {nombre}
task_generar_ctls_creation_error = [{task_id}] Error generando CTL para '{nombre}': {error}
task_generar_ctls_not_valid_file = [{task_id}] {nombre} no coincide con ningún prefijo
task_deleted_before_execution = tarea eliminada antes de ejecutarse
taskmanager_task_unremovable = [{task_id}] No se ha podido eliminar la tarea de task_manager. {error}
process_dir_deletion = [{task_id}] ERROR al eliminar ZIP y carpeta de trabajo: {error}
delete_task_wd_unremovable = [{task_id}] Error eliminando directorio de trabajo: {error}
delete_task_zip_unremovable = [{task_id}] No se ha podido eliminar el ZIP. {error}
worker_unreadable_queue = [{safe_id}] ERROR en lectura de cola: {error}
worker_cleanup_error = [{task_id}] ERROR en cleanup final: {error}
task_ejecutar_ctl_err = [{task_id}] ERROR en {nombre}
task_ejecutar_ctl_err_web = Error en CTL {nombre}
safe_clean_up_zip_err = [{task_id}] Error eliminando ZIP: {error}
safe_clean_up_dir_err = [{task_id}] Error eliminando directorio de trabajo: {error}
wrong_line_format = Línea mal formada en {nombre_fmt}: {linea}
task_error = [{task_id}] ERROR: {error}
task_traceback = ⚠️ Error en tarea {task_id}:\n{trace}

#TODO - no usados
invalid_csv_name = El fichero CSV '{nombre}' no tiene un nombre válido.
invalid_text_file = El fichero '{nombre}' no cumple el patrón esperado.
template_not_found = No existe plantilla para el fichero '{nombre}' (código {codigo}).
#TODO - no usados

[warning]
app_no_view_selected = No se especificó la vista para exportar.
queue_unremovevable_task = [{task_id}] No se ha podido eliminar de la cola. {error}
taskmanager_nowait = Excepción en task_manager.q.get_nowait(). {error}
task_comprobar_csv_falta = [{task_id}] CSV faltante para {nombre} se generará.
task_missing = ⚠️ [{task_id}] No se pudo guardar el estado de error porque la tarea ya no existe

[info]
app_loaded_view = Vista '{selected_view}' cargada correctamente.
app_tasks_removed = Todas las tareas fueron eliminadas
task_comprobar_csv_inicio = [{task_id}] Estado: comprobando existencia de ficheros CSV
task_comprobar_csv_encontrado = [{task_id}] CSV encontrado: {nombre}, se usará para generar el CTL
task_comprobar_csv_gen = [{task_id}] Generando CSV: {nombre_csv} usando formato {nombre_fmt}
task_comprobar_csv_gen_fin = [{task_id}] CSV generado: {nombre_csv}
task_comprobar_csv_fin = [{task_id}] Comprobación de CSVs finalizada
task_generar_ctls_inicio = [{task_id}] Inicio de tarea de generación de CTLs individuales por CSV…
task_generar_ctls_no_heading = ⚠️ El CSV '{nombre}' solo contiene cabecera. No se generará el CTL.
task_generar_ctls_prefix = [{task_id}] {filename} coincide con el prefijo: {table}
task_generar_ctls_ok = [{task_id}] CTL generado: {nombre}
task_ejecutar_ctls_ctl = [{task_id}] Ejecutando: {nombre}
task_ejecutar_ctls_end = [{task_id}] CTL cargado OK: {nombre}
task_ejecutar_ctls_end_web = Carga finalizada correctamente
task_ejecutar_ctls_end_log = [{task_id}] CARGA FINALIZADA
task_error_removed = Tarea eliminada tras error
task_final_state = ℹ️ [{task_id}] Estado final calculado: {state}
safe_clean_up_starting = [{task_id}] Iniciando cleanup...
safe_clean_up_removed_zip = [{task_id}] ZIP eliminado: {zip_path}
safe_clean_up_removed_dir = [{task_id}] Carpeta eliminada: {task_dir}
safe_clean_up_done = [{task_id}] Cleanup completado.

#TODO - no usados
file_match_prefix = El fichero '{nombre}' coincide con el prefijo '{prefijo}'.
#TODO - no usados

[process]
process_ejecutar_ctls = [{task_id}] Ejecutando SQL*Loader para cada CTL…
#TODO - no usados
process_started = Proceso iniciado para tarea {task_id}
process_completed = Proceso finalizado para tarea {task_id}
#TODO - no usados
